#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

subdir-ccflags-$(CONFIG_CAMERA_HW_BIG_DATA) += -I$(srctree)/drivers/misc/mediatek/include/hwparam
ccflags-y += -D$(MTK_PROJECT)
obj-y += imx258_pdafotp.o
obj-y += imx258mipiraw_Sensor.o
